http:
  port: 8091

grpc:
  port: 9091

redis:
  addr: "118.24.164.222:6379"
  password: "kelab666"
  db: 2
  pool_size: 50
  dial_timeout_seconds: 5
  read_timeout_seconds: 3
  write_timeout_seconds: 3

captcha:
  ttl_seconds: 120
  width: 320
  height: 180
  graph_size_min: 52
  graph_size_max: 64
  slider_tolerance: 8

token:
  ttl_seconds: 300
  secret: "CHANGE_ME"
